---
- name: Create Azure VM
  hosts: localhost
  tasks:
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: B2C6A
        name: Groep1_test_Vnet
        address_prefixes: 10.0.0.0/16
        subnet_prefix: 10.0.0.0/24
        state: present
         client_id: 07e8cb94-0fa9-4921-8592-7bc71c7673ad
        secret: -dl8Q~QTwbgmO5jpThtSe-lLLEKjcz.0N8C79aRB
        tenant: 586e785a-8271-4fc6-a0c4-59fec8a68975

    - name: Create public IP
      azure_rm_publicipaddress:
        resource_group: B2C6A
        allocation_method: Static
        name: Groep1_test_PublicIP
        state: present
        client_id: 07e8cb94-0fa9-4921-8592-7bc71c7673ad
        secret: -dl8Q~QTwbgmO5jpThtSe-lLLEKjcz.0N8C79aRB
        tenant: 586e785a-8271-4fc6-a0c4-59fec8a68975

    - name: Create network interface
      azure_rm_networkinterface:
        resource_group: B2C6A
        name: Groep1_test_NIC
        virtual_network: Groep1_test_Vnet
        public_ip_name: Groep1_test_PublicIP
        state: present
        client_id: 07e8cb94-0fa9-4921-8592-7bc71c7673ad
        secret: -dl8Q~QTwbgmO5jpThtSe-lLLEKjcz.0N8C79aRB
        tenant: 586e785a-8271-4fc6-a0c4-59fec8a68975

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: B2C6A
        name: Groep1_test_VM
        vm_size: StandardSSD_LRS
        admin_username: 07e8cb94-0fa9-4921-8592-7bc71c7673ad
        admin_password: -dl8Q~QTwbgmO5jpThtSe-lLLEKjcz.0N8C79aRB
        network_interfaces: Groep1_test_NIC
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
        state: present
        client_id: 07e8cb94-0fa9-4921-8592-7bc71c7673ad
        secret: -dl8Q~QTwbgmO5jpThtSe-lLLEKjcz.0N8C79aRB
        tenant: 586e785a-8271-4fc6-a0c4-59fec8a68975