version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: B2C6A
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  db-data:
