name: Review Request
on:
  pull_request:
    branches:    
      - main
jobs:
  discord-notifier:
    # Name of the enviroment
    environment: secrets
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sequence of tasks
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.WEBHOOKS_URL }}
